### ISSUE TITLE
Program crash on window click

### ISSUE THREAD

**Issue by unenergizer** [tommyettinger/gdx-liftoff#50]
I generated my project. It popped open a window giving me some information about the project. I attempted to copy the information so I can save it in notepad for later. When I clicked in the window the program crashed.

Here is the stracktrace.

`java -jar gdx-liftoff-1.10.0.5.jar
Exception in thread "main" java.lang.IndexOutOfBoundsException: index can't be >= size: 617 >= 606
        at com.badlogic.gdx.utils.FloatArray.get(FloatArray.java:131)
        at com.kotcrab.vis.ui.widget.VisTextArea.drawSelection(VisTextArea.java:250)
        at com.kotcrab.vis.ui.widget.VisTextField.draw(VisTextField.java:350)
        at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:111)
        at com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.draw(ScrollPane.java:543)
        at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:124)
        at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
        at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:170)
        at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:126)
        at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:111)
        at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:117)
        at com.badlogic.gdx.scenes.scene2d.ui.Window.draw(Window.java:253)
        at com.kotcrab.vis.ui.widget.VisWindow.draw(VisWindow.java:239)
        at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:111)
        at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
        at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:129)
        at com.github.czyzby.autumn.mvc.component.ui.controller.impl.StandardViewRenderer.render(StandardViewRenderer.java:13)
        at com.github.czyzby.autumn.mvc.component.ui.controller.impl.AnnotatedViewController.render(AnnotatedViewController.java:165)
        at com.github.czyzby.autumn.mvc.component.ui.InterfaceService.render(InterfaceService.java:467)
        at com.github.czyzby.autumn.mvc.application.AutumnApplication.render(AutumnApplication.java:139)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:403)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:143)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
        at com.github.czyzby.setup.MainKt.main(main.kt:87)
        at com.github.czyzby.setup.MainKt.main(main.kt)`

**Comment by tommyettinger** [comment]
This should be fixed now; the next release will have some basic handling to avoid a crash during selection. The issue has been known for a while in VisUI ([see here](https://github.com/kotcrab/vis-ui/issues/348)), and in libGDX itself (I believe there have been several issues). Color markup seems to just outright break selection in TextArea widgets, in both libGDX and VisUI. With the latest code, there's some exception handling for this exact case, and when it detects this specific error, it copies the whole text to the clipboard and continues rendering other widgets. The selected area may look odd for a little while though, because it is failing to render. Since that part is the libGDX bug, it's going to be harder to fix.
